// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, z, hop, uic, p, be, T, F;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print;
  z = com.z, hop = com.hop, uic = com.uic;
  p = print.fail("test/test.js");
  be = valleydate;
  T = function(x){
    return true;
  };
  F = function(x){
    if (x === 'world') {
      return [false, 'foo'];
    } else {
      return true;
    }
  };
}).call(this);
