// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, z, hop, slist, p, be, T, F;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print;
  z = com.z, hop = com.hop, slist = com.slist;
  p = print.fail("test/test.js");
  be = valleydate;
  T = function(x){
    return true;
  };
  F = function(x){
    return [false, 'foobar'];
  };
  z(be);
}).call(this);
