// Generated by LiveScript 1.6.0
(function(){
  var common, print, IS, z, j, noop, p, SA, main, ret, e;
  common = require("../dist/common");
  print = require("../dist/print");
  IS = require("../dist/main");
  z = common.z, j = common.j, noop = common.noop;
  p = print.fail("test/test3.js");
  SA = IS.string.or(IS.array.or(IS.number));
  main = IS.object.on("chokidar", IS.object.on("path", SA));
  ret = main({
    chokidar: {}
  });
  try {
    if (!(ret.message[2][2][0] === ":or")) {
      p(":or is not present in (deep) .message");
    }
  } catch (e$) {
    e = e$;
    p("something has gone wrong with .message");
  }
}).call(this);
