// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, z, l, hop, slist, R, p, be, T, F, data, V;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print;
  z = com.z, l = com.l, hop = com.hop, slist = com.slist, R = com.R;
  p = print.fail("test/test.js");
  be = valleydate;
  T = function(x){
    return true;
  };
  F = function(x){
    return [false, 'foobar'];
  };
  data = {
    foo: {
      bar: "hello world"
    }
  };
  V = be.obj.alt(be.arr, be.num).cont(function(x){
    return z(x);
  });
  z(V.auth(1));
}).call(this);
