// Generated by LiveScript 1.6.0
(function(){
  var common, print, be, z, j, noop, p, SA, main, ret, e;
  common = require("../dist/common");
  print = require("../dist/print");
  be = require("../dist/main");
  z = common.z, j = common.j, noop = common.noop;
  p = print.fail("test/test3.js");
  SA = be.str.or(be.arr.or(be.num));
  main = be.obj.on("chokidar", be.obj.on("path", SA));
  ret = main({
    chokidar: {}
  });
  try {
    if (!(ret.path.join(".") === "chokidar.path")) {
      p(".path is mangled");
    }
  } catch (e$) {
    e = e$;
    p("something has gone wrong with .path");
  }
}).call(this);
