// Generated by LiveScript 1.6.0
(function(){
  var common, print, IS, z, j, noop, p, inn, main, example, ret, msg, cor, e;
  common = require("../dist/common");
  print = require("../dist/print");
  IS = require("../dist/main");
  z = common.z, j = common.j, noop = common.noop;
  p = print.fail("test/test4.js");
  inn = IS.string.or(IS.number.or(IS.obj.on("age", IS.number)));
  main = IS.obj.map(inn);
  example = {
    'adam': 22,
    'charles': 35,
    'henry': {
      age: 'foobar'
    },
    'joe': 33
  };
  ret = main(example);
  try {
    msg = ret.message[3];
    cor = 0;
    cor += msg[0] === ":on";
    cor += msg[1] === "age";
    cor += msg[2] === "not a number";
    if (!(cor === 2)) {
      p("something went wrong with .map");
    }
  } catch (e$) {
    e = e$;
    p("something has gone wrong with .message");
  }
}).call(this);
