// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, z, hop, j, p, be, T, F, V, ret;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print;
  z = com.z, hop = com.hop, j = com.j;
  p = print.fail("test/test5.js");
  be = valleydate;
  T = function(x){
    return true;
  };
  F = function(x){
    return [false, 'foobar'];
  };
  V = be.arr.map(be.str).or(be.str).or(be.obj).and(F);
  ret = V.auth(null);
  if (!(ret.message[0][0] === "not array")) {
    p();
  }
}).call(this);
