// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, pkg, z, hop, p;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print, pkg = reg.pkg;
  z = com.z, hop = com.hop;
  p = print.fail("test/test6.js");
}).call(this);
