// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, z, hop, p, be, T, F, V, ret;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print;
  z = com.z, hop = com.hop;
  p = print.fail("test/test5.js");
  be = valleydate;
  T = function(x){
    return true;
  };
  F = function(x){
    return [false, 'foobar'];
  };
  V = be.arr.map(be.str).or(be.str).and(F);
  ret = V(null);
  if (!(ret.message === "not string")) {
    p();
  }
}).call(this);
