// Generated by LiveScript 1.6.0
(function(){
  var common, print, IS, z, j, noop, pp, p, SA, main;
  common = require("../dist/common");
  print = require("../dist/print");
  IS = require("../dist/main");
  z = common.z, j = common.j, noop = common.noop;
  pp = common.pp;
  p = print.fail("test/test3.js");
  SA = IS.string.or(IS.array.dis(function(){
    return z(":hello from dis");
  }));
  main = IS.object.on("chokidar", IS.object.on("path", SA));
  z(SA(null));
}).call(this);
