// Generated by LiveScript 1.6.0
(function(){
  var ref$, z, noops, print, IS, p, G7, valG7, isG7, ret1, ret2;
  ref$ = require("../dist/common"), z = ref$.z, noops = ref$.noops;
  print = require("../dist/print");
  IS = require("../dist/main");
  p = print.fail("test/test1.js");
  G7 = new Set(["USA", "EU", "UK", "Japan", "Italy", "Germany", "France"]);
  valG7 = function(s){
    if (G7.has(s)) {
      return true;
    } else {
      return [false, "not in G7"];
    }
  };
  isG7 = IS.string.and(valG7);
  ret1 = isG7("UK");
  ret2 = isG7("Spain");
  if (!(ret1.value === 'UK')) {
    p();
  }
  if (!(Array.isArray(ret2.message) && ret2.message[0] === "not in G7")) {
    p();
  }
  if (ret2.value === undefined) {
    p(".value has not been passed to {..error:true..}.");
  }
}).call(this);
