// Generated by LiveScript 1.6.0
(function(){
  var reg, valleydate, com, print, z, l, hop, slist, R, p, be, wait, T, F, V, ret;
  reg = require("../dist/registry");
  valleydate = require("../dist/main");
  com = reg.com, print = reg.print;
  z = com.z, l = com.l, hop = com.hop, slist = com.slist, R = com.R;
  p = print.fail("test/test7.js");
  be = valleydate;
  wait = function(t, f){
    return setTimeout(f, t);
  };
  T = function(x){
    return true;
  };
  F = function(x){
    return [false, 'foobar'];
  };
  V = be.restricted([0, 1]);
  ret = V.auth(['a', 'b', 'c']);
  if (!(ret.message[0] === 'res')) {
    p(".restricted message is not accurate.");
  }
}).call(this);
