// Generated by LiveScript 1.6.0
(function(){
  var ref$, z, noops, print, IS, p, address, V, sample, ret;
  ref$ = require("../dist/common"), z = ref$.z, noops = ref$.noops;
  print = require("../dist/print");
  IS = require("../dist/main");
  p = print.fail("test/test1.js");
  address = IS.required('city').on('city', IS.string).on('country', IS.string.fix('France'));
  V = IS.required('address', 'name', 'age').on('address', address).on('name', IS.string).on('age', IS.number);
  sample = {
    name: "Fred",
    age: 30,
    address: {
      city: "foocity",
      country: null
    }
  };
  ret = V(sample);
  if (!(ret.value.address.country === 'France')) {
    p();
  }
}).call(this);
