name: valleydate
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/valleydate#readme.md
license: BSD-3-Clause
description: immutable object validator
repository: https://github.com/sourcevault/valleydate.git
version: 0.0.49
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  "@aitodotai/json-stringify-pretty-compact": "*"
  pretty-error: "2.1.1"
  cli-color: "2.0.0"
  hoplon: "*"
  ramda: "0.26.1"
  flat: "*"
  deep-freeze: "*"
  dot-prop: "*"
keywords:
  - "json-schema-validator"
  - "schema-validator"
  - "error-messages"
  - "type-check"
  - "functional"
  - "validator"
  - "chainable"
  - "immutable"
  - "validate"
  - "objects"
  - "monadic"
  - "mostjs"
  - "simple"
  - "schema"
  - "types"
  - "Array"
  - "monad"
  - "JSON"