name: valleydate
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/valleydate#readme.md
license: MIT
description: immutable object validator
repository: https://github.com/sourcevault/valleydate.git
version: 0.0.42
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  ramda: "0.26.1"
  pretty-error: "2.1.1"
  hoplon: "*"
  "@aitodotai/json-stringify-pretty-compact": "*"
  cli-color: "2.0.0"
keywords:
  - "schema"
  - "validator"
  - "JSON"
  - "schema-validator"
  - "json-schema-validator"
  - "validate"
  - "simple"
  - "type-check"
  - "types"
  - "objects"
  - "monadic"
  - "functional"
  - "Array"
  - "error-messages"
  - "mostjs"
  - "immutable"
  - "chainable"
  - "monad"