name: valleydate
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/valleydate#readme.md
license: BSD-3-Clause
description: immutable object validator
repository: https://github.com/sourcevault/valleydate.git
version: 0.1.20
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  hoplon: 0.0.44
  "@sourcevault/utils.common": 0.0.5
keywords:
  - "json-schema-validator"
  - "schema-validator"
  - "error-messages"
  - "type-check"
  - "functional"
  - "validator"
  - "chainable"
  - "immutable"
  - "validate"
  - "objects"
  - "monadic"
  - "mostjs"
  - "simple"
  - "schema"
  - "types"
  - "Array"
  - "monad"
  - "JSON"